name: reusable-get-modified-packages

on:
  workflow_call:
    inputs:
      script-ref:
        required: true
        type: string
    outputs:
      modified-packages:
        value: ${{ jobs.get-modified-packages.outputs.modified-packages }}

jobs:
  get-modified-packages:
    runs-on: ubuntu-latest
    container: ros:galactic
    outputs:
      modified-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetch with depth=0 to find modified packages
          fetch-depth: 0

      - name: Install curl
        run: |
          apt-get -y update
          apt-get -y install curl

      - name: Retrieve get-modified-packages script
        run: |
          curl -fsSL -o get-modified-packages.sh \
            https://raw.githubusercontent.com/autowarefoundation/autoware-github-actions/${{ inputs.script-ref }}/.github/get-modified-packages.sh
          chmod +x get-modified-packages.sh

      - name: Get modified packages
        id: get-modified-packages
        run: |
          ./get-modified-packages.sh origin/${{ github.base_ref }}

      - name: Show result
        run: |
          echo "modified packages: ${{ steps.get-modified-packages.outputs.modified-packages }}"
