name: reusable-get-modified-source-files

on:
  workflow_call:
    outputs:
      modified-source-files:
        value: ${{ jobs.get-modified-source-files.outputs.modified-source-files }}

jobs:
  get-modified-source-files:
    runs-on: ubuntu-latest
    outputs:
      modified-source-files: ${{ steps.get-modified-source-files.outputs.modified-source-files }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetch with depth=0 to find modified files
          fetch-depth: 0

      - name: Get modified source files
        id: get-modified-source-files
        run: |
          # List added/modified/renamed files excluding deleted ones
          modified_files=$(git --no-pager diff --name-only --diff-filter=d origin/"${{ github.base_ref }}"...HEAD)
          modified_source_files=$(echo "$modified_files" | egrep "\.(cpp|hpp)$") || true
          echo ::set-output name=modified-source-files::${modified_source_files}

      - name: Show result
        run: |
          echo "modified source files: ${{ steps.get-modified-source-files.outputs.modified-source-files }}"
