name: reusable-get-self-packages

on:
  workflow_call:
    outputs:
      self-packages:
        value: ${{ jobs.get-self-packages.outputs.self-packages }}

jobs:
  get-self-packages:
    runs-on: ubuntu-latest
    container: ros:galactic
    outputs:
      self-packages: ${{ steps.get-self-packages.outputs.self-packages }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get packages in this repository
        id: get-self-packages
        run: |
          echo ::set-output name=self-packages::$(colcon list --names-only)

      - name: Show result
        run: |
          echo "self packages: ${{ steps.get-self-packages.outputs.self-packages }}"
